/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dietadvisor;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
       jPasswordFieldpswd.setVisible(false);
       jLabelPassword.setVisible(false);
       jButtonSign.setVisible(false);
       jTextFieldserial.setEditable(true);
       jButtonVerification.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jLabelSerial = new javax.swing.JLabel();
        jTextFieldserial = new javax.swing.JTextField();
        jButtonVerification = new javax.swing.JButton();
        jPasswordFieldpswd = new javax.swing.JPasswordField();
        jLabelPassword = new javax.swing.JLabel();
        jButtonSign = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitle.setFont(new java.awt.Font("Tekton Pro", 3, 48)); // NOI18N
        jLabelTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LOGO.png"))); // NOI18N
        jPanel1.add(jLabelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 400, 180));

        jLabelSerial.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabelSerial.setText("SERIAL NO");
        jPanel1.add(jLabelSerial, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jTextFieldserial.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jPanel1.add(jTextFieldserial, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 279, 37));

        jButtonVerification.setBackground(new java.awt.Color(204, 0, 0));
        jButtonVerification.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jButtonVerification.setText("VERIFY");
        jButtonVerification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVerificationMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonVerification, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jPasswordFieldpswd.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jPanel1.add(jPasswordFieldpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 279, 36));

        jLabelPassword.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jLabelPassword.setText("PASSWORD");
        jPanel1.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jButtonSign.setBackground(new java.awt.Color(204, 0, 0));
        jButtonSign.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jButtonSign.setText("SIGN IN");
        jButtonSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSignMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 85, -1));

        jButtonBack.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBack.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jButtonBack.setText("BACK");
        jButtonBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jButtonBack.setBorderPainted(false);
        jButtonBack.setContentAreaFilled(false);
        jButtonBack.setFocusPainted(false);
        jButtonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBackMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 11, 52, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hos.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVerificationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVerificationMouseClicked
       Connection con;
       PreparedStatement ps;
       try{
       con=connection.getConnection();
       ps=con.prepareStatement("SELECT * FROM admin WHERE SerialNo= "+jTextFieldserial.getText());
       ResultSet rst=ps.executeQuery();
       if(rst.next()){
       jPasswordFieldpswd.setVisible(true);
       jLabelPassword.setVisible(true);
       jButtonSign.setVisible(true);
       jTextFieldserial.setEditable(false);
       jButtonVerification.setVisible(false);
      
               
       }
       else{
       JOptionPane.showMessageDialog(null,"INCORRECT LOG IN CREDENTIALS");
       
       } 
       }catch(Exception ex){
       System.out.println(ex);
       }
       
    }//GEN-LAST:event_jButtonVerificationMouseClicked

    private void jButtonSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSignMouseClicked
         Connection con;
       PreparedStatement ps;
       try{
       con=connection.getConnection();
       ps=con.prepareStatement("Select * from admin where SerialNo='" + jTextFieldserial.getText() + "'and  password='" + jPasswordFieldpswd.getText() +"'");
       ResultSet rst=ps.executeQuery();
       if(rst.next()){
       jPasswordFieldpswd.setVisible(true);
       jLabelPassword.setVisible(true);
       jButtonSign.setVisible(true);
       jTextFieldserial.setEditable(false);
       jButtonVerification.setVisible(false);
       Doctor dr=new Doctor();
        dr.main(null);
        this.dispose();
               
       }
       else{
       JOptionPane.showMessageDialog(null,"INCORRECT LOG IN CREDENTIALS");
       
       } 
       }catch(Exception ex){
       System.out.println(ex);
       }
       
    }//GEN-LAST:event_jButtonSignMouseClicked

    private void jButtonBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBackMouseClicked
        index index=new index();
        index.main(null);
        this.dispose();
    }//GEN-LAST:event_jButtonBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */ 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSign;
    private javax.swing.JButton jButtonVerification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelSerial;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldpswd;
    private javax.swing.JTextField jTextFieldserial;
    // End of variables declaration//GEN-END:variables
}
