/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dietadvisor;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import static java.time.Instant.now;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PatientPanel extends javax.swing.JFrame {
String luname;
    /**
     * Creates new form PatientPanel1
     */
    public PatientPanel() {
initComponents();
        jTextFieldUserNamep.setText(patient.jTextFieldUserName.getText());
        
        
//        patient patientObject=new patient();
//        patientObject.getFname();
        
//        jTextFieldUserNamep.setText(patientObject.getFname());
//jTextFieldUserNamep.setText("magy");      
//jTextFieldUserNamep.setVisible(true);
        
        
//        jLabelTitle1Username.setText();
        //
    }
      
    public PatientPanel(String uname){
        
    this.luname=uname;
    jTextFieldUserNamep.setText(uname);
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonSubmit2 = new javax.swing.JButton();
        jLabelTBMI = new javax.swing.JLabel();
        jLabelheight = new javax.swing.JLabel();
        jTextFieldHeight = new javax.swing.JTextField();
        jLabelTitle2 = new javax.swing.JLabel();
        jComboBoxVitamin3 = new javax.swing.JComboBox<>();
        jLabelProtein2 = new javax.swing.JLabel();
        jComboBoxVitamins = new javax.swing.JComboBox<>();
        jLabelBMI = new javax.swing.JLabel();
        jComboBoxProteins = new javax.swing.JComboBox<>();
        jButtonSubmit = new javax.swing.JButton();
        jLabelWeight = new javax.swing.JLabel();
        jLabelsupper = new javax.swing.JLabel();
        jLabelVitamins = new javax.swing.JLabel();
        jLabelProtein3 = new javax.swing.JLabel();
        jComboBoxCarbohydrates2 = new javax.swing.JComboBox<>();
        jLabelProtein = new javax.swing.JLabel();
        jComboBoxCabohydrates1 = new javax.swing.JComboBox<>();
        jLabelVitamin3 = new javax.swing.JLabel();
        jLabelCabohydrates = new javax.swing.JLabel();
        jComboBoxProtein2 = new javax.swing.JComboBox<>();
        jLabelVitamin2 = new javax.swing.JLabel();
        jButtonCheck = new javax.swing.JButton();
        jComboBoxCarbohydrate3 = new javax.swing.JComboBox<>();
        jLabelLunch = new javax.swing.JLabel();
        jLabelCabohydrates2 = new javax.swing.JLabel();
        jLabelBreakfast = new javax.swing.JLabel();
        jComboBoxVitamin2 = new javax.swing.JComboBox<>();
        jLabelName = new javax.swing.JLabel();
        jComboBoxProtein1 = new javax.swing.JComboBox<>();
        jTextFieldWeight = new javax.swing.JTextField();
        jTextFieldUserNamep = new javax.swing.JLabel();
        jLabelCabohydrates3 = new javax.swing.JLabel();
        JtextFieldBMI = new javax.swing.JTextField();
        jButtonSubmit3 = new javax.swing.JButton();
        jLabelKg = new javax.swing.JLabel();
        jLabelM = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSubmit2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jButtonSubmit2.setText("SUBMIT");
        jButtonSubmit2.setContentAreaFilled(false);
        jButtonSubmit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubmit2MouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSubmit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 425, -1, -1));

        jLabelTBMI.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabelTBMI.setText("BMI");
        jPanel1.add(jLabelTBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 11, 44, -1));

        jLabelheight.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabelheight.setText("HEIGHT");
        jPanel1.add(jLabelheight, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 46, 89, -1));

        jTextFieldHeight.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldHeight.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldHeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 43, 130, -1));

        jLabelTitle2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelTitle2.setText("RECOMMENDED PORTIONS");
        jPanel1.add(jLabelTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 163, 198, -1));

        jComboBoxVitamin3.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        jComboBoxVitamin3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "........" }));
        jPanel1.add(jComboBoxVitamin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 398, -1, -1));

        jLabelProtein2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabelProtein2.setText("PROTEIN");
        jPanel1.add(jLabelProtein2, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 320, 58, -1));

        jComboBoxVitamins.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        jComboBoxVitamins.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "........" }));
        jPanel1.add(jComboBoxVitamins, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 398, -1, -1));

        jLabelBMI.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        jLabelBMI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.add(jLabelBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 67, 215, 29));

        jComboBoxProteins.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        jComboBoxProteins.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "......." }));
        jComboBoxProteins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxProteinsMouseClicked(evt);
            }
        });
        jComboBoxProteins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProteinsActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxProteins, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 327, -1, -1));

        jButtonSubmit.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jButtonSubmit.setText("SUBMIT");
        jButtonSubmit.setBorderPainted(false);
        jButtonSubmit.setContentAreaFilled(false);
        jButtonSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubmitMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 425, -1, -1));

        jLabelWeight.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jLabelWeight.setText("WEIGHT");
        jPanel1.add(jLabelWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 14, 89, -1));

        jLabelsupper.setFont(new java.awt.Font("Tekton Pro", 0, 15)); // NOI18N
        jLabelsupper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/supper.png"))); // NOI18N
        jLabelsupper.setText("SUPPER");
        jPanel1.add(jLabelsupper, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 241, 128, -1));

        jLabelVitamins.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabelVitamins.setText("VITAMIN");
        jPanel1.add(jLabelVitamins, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 399, -1, -1));

        jLabelProtein3.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabelProtein3.setText("PROTEIN");
        jPanel1.add(jLabelProtein3, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 322, -1, -1));

        jComboBoxCarbohydrates2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBoxCarbohydrates2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "......." }));
        jComboBoxCarbohydrates2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCarbohydrates2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCarbohydrates2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 356, -1, -1));

        jLabelProtein.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabelProtein.setText("PROTEIN");
        jPanel1.add(jLabelProtein, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 328, -1, -1));

        jComboBoxCabohydrates1.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        jComboBoxCabohydrates1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "......." }));
        jPanel1.add(jComboBoxCabohydrates1, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 364, -1, -1));

        jLabelVitamin3.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabelVitamin3.setText("VITAMIN");
        jPanel1.add(jLabelVitamin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 399, -1, -1));

        jLabelCabohydrates.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabelCabohydrates.setText("CABOHYDRATES");
        jPanel1.add(jLabelCabohydrates, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 365, -1, -1));

        jComboBoxProtein2.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        jComboBoxProtein2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "......." }));
        jComboBoxProtein2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProtein2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxProtein2, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 321, -1, -1));

        jLabelVitamin2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabelVitamin2.setText("VITAMIN");
        jPanel1.add(jLabelVitamin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 399, 50, -1));

        jButtonCheck.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jButtonCheck.setText("CHECK");
        jButtonCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCheckMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 74, -1, -1));

        jComboBoxCarbohydrate3.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        jComboBoxCarbohydrate3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "......." }));
        jPanel1.add(jComboBoxCarbohydrate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 358, -1, -1));

        jLabelLunch.setFont(new java.awt.Font("Tekton Pro", 0, 15)); // NOI18N
        jLabelLunch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lunch.png"))); // NOI18N
        jLabelLunch.setText("LUNCH");
        jPanel1.add(jLabelLunch, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 238, 120, -1));

        jLabelCabohydrates2.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabelCabohydrates2.setText("CABOHYDRATES");
        jPanel1.add(jLabelCabohydrates2, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 359, -1, -1));

        jLabelBreakfast.setFont(new java.awt.Font("Tekton Pro", 0, 15)); // NOI18N
        jLabelBreakfast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/coffee-cup.png"))); // NOI18N
        jLabelBreakfast.setText("BREAKFAST");
        jPanel1.add(jLabelBreakfast, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 236, -1, -1));

        jComboBoxVitamin2.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        jComboBoxVitamin2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "........" }));
        jPanel1.add(jComboBoxVitamin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 398, -1, -1));

        jLabelName.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jPanel1.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(813, 453, 276, 22));

        jComboBoxProtein1.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jComboBoxProtein1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "......." }));
        jPanel1.add(jComboBoxProtein1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 317, -1, -1));

        jTextFieldWeight.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldWeight.setFont(new java.awt.Font("Tekton Pro", 0, 18)); // NOI18N
        jTextFieldWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldWeightActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 11, 130, -1));

        jTextFieldUserNamep.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUserNamep.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jTextFieldUserNamep.setOpaque(true);
        jPanel1.add(jTextFieldUserNamep, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 392, 35));

        jLabelCabohydrates3.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jLabelCabohydrates3.setText("CABOHYDRATES");
        jPanel1.add(jLabelCabohydrates3, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 359, -1, -1));

        JtextFieldBMI.setEditable(false);
        JtextFieldBMI.setBackground(new java.awt.Color(204, 255, 204));
        JtextFieldBMI.setFont(new java.awt.Font("Tekton Pro", 0, 12)); // NOI18N
        JtextFieldBMI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(JtextFieldBMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 112, 314, 27));

        jButtonSubmit3.setFont(new java.awt.Font("Tekton Pro", 0, 14)); // NOI18N
        jButtonSubmit3.setText("SUBMIT");
        jButtonSubmit3.setBorderPainted(false);
        jButtonSubmit3.setContentAreaFilled(false);
        jButtonSubmit3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSubmit3MouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSubmit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(728, 423, -1, -1));

        jLabelKg.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelKg.setText("Kg(s)");
        jPanel1.add(jLabelKg, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 11, -1, -1));

        jLabelM.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabelM.setText("Meters");
        jPanel1.add(jLabelM, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 49, -1, -1));

        jLabelExit.setBackground(new java.awt.Color(255, 255, 255));
        jLabelExit.setFont(new java.awt.Font("Tekton Pro", 3, 18)); // NOI18N
        jLabelExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jLabelExit.setText("BACK");
        jLabelExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, null, null));
        jLabelExit.setOpaque(true);
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 11, 99, 40));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 186, 354, 32));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 910, 150));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 204, 0));
        jMenuBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenuBar1.setForeground(new java.awt.Color(153, 0, 0));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/man.png"))); // NOI18N
        jMenu1.setText("INFO");

        jMenuItem1.setText("BIO-DATA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("NOTIFICATION");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 919, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCheckMouseClicked
        //calculate BMI

        String W=jTextFieldWeight.getText();
        String H=jTextFieldHeight.getText();

        float weight=Float.parseFloat(W);
        float height=Float.parseFloat(H);

        float BMI;

        BMI = weight / (height*height);
        jLabelBMI.setText("BMI "+BMI);
        if(BMI<18.5){
            JtextFieldBMI.setText( "YOU ARE UNDERWEIGHT!");
        }
        else if (BMI>=18.5 && BMI <=25){
            JtextFieldBMI.setText("YOUR WEIGHT IS NORMAL");
        }
        else if(BMI>25 && BMI <=30){
            JtextFieldBMI.setText("YOU ARE OVERWEIGHT!");
        }
        else {
            JtextFieldBMI.setText("YOU ARE OBESE!");
        }
        

        //end of calculation
        Connection con;
        PreparedStatement ps;
        //BREAKFAST
        try{
           con=connection.getConnection();
            

            Statement stmt=con.createStatement();
            ResultSet rst=stmt.executeQuery("SELECT Protein FROM hiv");
            while(rst.next()){
                String protein=rst.getString(1);
                jComboBoxProteins.addItem(protein);
            }
            //
           
            stmt=con.createStatement();
            rst=stmt.executeQuery("SELECT Carbohydrates FROM hiv");
            while(rst.next()){
                String cab=rst.getString(1);
                jComboBoxCabohydrates1.addItem(cab);
            }
           
            stmt=con.createStatement();
             rst=stmt.executeQuery("SELECT Vitamins FROM hiv");
            while(rst.next()){
                String vit=rst.getString(1);
                 jComboBoxVitamins.addItem(rst.getString(1));
            }
        
        }
        catch(Exception e){System.out.println("err: "+e);}
        //BREAKFAST END
         //lunch
        try{
           con=connection.getConnection();
            

            Statement stmt=con.createStatement();
            ResultSet rst=stmt.executeQuery("SELECT Protein FROM hiv");
            while(rst.next()){
                String protein=rst.getString(1);
                jComboBoxProtein1.addItem(protein);
            }
            //
           
            stmt=con.createStatement();
            rst=stmt.executeQuery("SELECT Carbohydrates FROM hiv");
            while(rst.next()){
                String cab=rst.getString(1);
                jComboBoxCarbohydrates2.addItem(cab);
            }
           
            stmt=con.createStatement();
             rst=stmt.executeQuery("SELECT Vitamins FROM hiv");
            while(rst.next()){
                String vit=rst.getString(1);
                jComboBoxVitamin2.addItem(rst.getString(1));
            }
        con.close();
        }
        catch(Exception e){System.out.println("err: "+e);}
        //
        //LUNCH END
        //
        //SUPPER
        try{
           con=connection.getConnection();
            

            Statement stmt=con.createStatement();
            ResultSet rst=stmt.executeQuery("SELECT Protein FROM hiv");
            while(rst.next()){
                String protein=rst.getString(1);
                jComboBoxProtein2.addItem(protein);
            }
            //
           
            stmt=con.createStatement();
            rst=stmt.executeQuery("SELECT Carbohydrates FROM hiv");
            while(rst.next()){
                String cab=rst.getString(1);
                jComboBoxCarbohydrate3.addItem(cab);
            }
           
            stmt=con.createStatement();
             rst=stmt.executeQuery("SELECT Vitamins FROM hiv");
            while(rst.next()){
                String vit=rst.getString(1);
                 jComboBoxVitamin3.addItem(rst.getString(1));
            }
        con.close();
        }
        catch(Exception e){System.out.println("err: "+e);
        
        }
        //
        con=connection.getConnection();
    try {
        ps=con.prepareStatement("INSERT INTO progress(BMI) VALUES("+jLabelBMI.getText()+")");

        ps.executeUpdate();
        
    } catch (SQLException ex) {
        Logger.getLogger(PatientPanel.class.getName()).log(Level.SEVERE, null, ex);
    }

    }//GEN-LAST:event_jButtonCheckMouseClicked

    private void jButtonSubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubmitMouseClicked
        Connection con;
        PreparedStatement ps;
        try{
            con=connection.getConnection();
            
            ps=con.prepareStatement("insert into meals(NAME,DATE,BREAKFAST) VALUES(?,?,?)");
           
            ps.setString(1, jTextFieldUserNamep.getText());
            DateTimeFormatter dtf=DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDateTime now=LocalDateTime.now();
            ps.setString(2,dtf.format(now));
            ps.setString(3, jComboBoxProteins.getSelectedItem().toString()+",\n "+jComboBoxCabohydrates1.getSelectedItem().toString()+",\n"+jComboBoxVitamins.getSelectedItem().toString());
//            ps.setString(3,);
           
            int i=ps.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null,"SUBMIT DATA....?");
                jLabelBreakfast.setVisible(false);
                jComboBoxProteins.setVisible(false);
                jComboBoxCabohydrates1.setVisible(false);
                jComboBoxVitamins.setVisible(false);
                jButtonSubmit.setVisible(false);
                jLabelProtein.setVisible(false);
                jLabelCabohydrates.setVisible(false);
                jLabelVitamins.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null,"NETWORK ERROR PLEASE TRY AGAIN");
            }
            con.close();
        }catch(Exception ex){
            System.out.println("err: "+ex);
        }
    }//GEN-LAST:event_jButtonSubmitMouseClicked

    private void jComboBoxProteinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProteinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProteinsActionPerformed

    private void jButtonSubmit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubmit2MouseClicked
        Connection con;
        PreparedStatement ps;
        try{
            con=connection.getConnection();
            
            ps=con.prepareStatement("UPDATE meals set NAME=?,DATE=?,SUPPER=? WHERE NAME= "+jTextFieldUserNamep.getText());
           
           ps.setString(1, jTextFieldUserNamep.getText());
            DateTimeFormatter dtf=DateTimeFormatter.ofPattern("yyyy/MM/dd");
            LocalDateTime now=LocalDateTime.now();
            ps.setString(2,dtf.format(now)); 
            ps.setString(3, jComboBoxProtein1.getSelectedItem().toString()+",\n "+jComboBoxCarbohydrates2.getSelectedItem().toString()+",\n "+jComboBoxVitamin2.getSelectedItem().toString());
       

            int i=ps.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null,"SUBMIT DATA....?");
                jComboBoxProtein1.setVisible(false);
                jLabelLunch.setVisible(true);
                jComboBoxCarbohydrates2.setVisible(false);
                jComboBoxVitamin2.setVisible(false);
                jButtonSubmit2.setVisible(false);
               
                
            }
            else{
                JOptionPane.showMessageDialog(null,"NETWORK ERROR PLEASE TRY AGAIN");
            }
            con.close();
        }catch(Exception ex){
            System.out.println("err: "+ex);
        }
    }//GEN-LAST:event_jButtonSubmit2MouseClicked

    private void jButtonSubmit3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSubmit3MouseClicked
       Connection con;
        PreparedStatement ps;
        try{
            con=connection.getConnection();
            
            ps=con.prepareStatement("UPDATE meals set NAME=?,DATE=?,BREAKFAST=? WHERE NAME= "+jTextFieldUserNamep.getText());
           
            ps.setString(1, jTextFieldUserNamep.getText());
            
            ps.setString(3, jComboBoxProtein2.getSelectedItem().toString()+" "+jComboBoxCarbohydrate3.getSelectedItem().toString()+" "+jComboBoxVitamin2.getSelectedItem().toString());
            

            int i=ps.executeUpdate();
            if(i>0){
                JOptionPane.showConfirmDialog(null,"SUBMIT DATA....?");
                jComboBoxProtein1.setVisible(false);
                jLabelLunch.setVisible(false);
                jComboBoxCarbohydrate3.setVisible(false);
                jComboBoxVitamin3.setVisible(false);
                jComboBoxProtein2.setVisible(false);
                jButtonSubmit3.setVisible(false);
                
            }
            else{
                JOptionPane.showMessageDialog(null,"NETWORK ERROR PLEASE TRY AGAIN");
            }
            con.close();
        }catch(Exception ex){
            System.out.println("err: "+ex);
        }
    }//GEN-LAST:event_jButtonSubmit3MouseClicked

    private void jTextFieldWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldWeightActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jComboBoxProteinsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxProteinsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProteinsMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        index index=new index();
        index.main(null);
        this.dispose();
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jComboBoxProtein2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProtein2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProtein2ActionPerformed

    private void jComboBoxCarbohydrates2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCarbohydrates2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCarbohydrates2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientPanel().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtextFieldBMI;
    private javax.swing.JButton jButtonCheck;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JButton jButtonSubmit2;
    private javax.swing.JButton jButtonSubmit3;
    private javax.swing.JComboBox<String> jComboBoxCabohydrates1;
    private javax.swing.JComboBox<String> jComboBoxCarbohydrate3;
    private javax.swing.JComboBox<String> jComboBoxCarbohydrates2;
    private javax.swing.JComboBox<String> jComboBoxProtein1;
    private javax.swing.JComboBox<String> jComboBoxProtein2;
    private javax.swing.JComboBox<String> jComboBoxProteins;
    private javax.swing.JComboBox<String> jComboBoxVitamin2;
    private javax.swing.JComboBox<String> jComboBoxVitamin3;
    private javax.swing.JComboBox<String> jComboBoxVitamins;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBMI;
    private javax.swing.JLabel jLabelBreakfast;
    private javax.swing.JLabel jLabelCabohydrates;
    private javax.swing.JLabel jLabelCabohydrates2;
    private javax.swing.JLabel jLabelCabohydrates3;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelKg;
    private javax.swing.JLabel jLabelLunch;
    private javax.swing.JLabel jLabelM;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelProtein;
    private javax.swing.JLabel jLabelProtein2;
    private javax.swing.JLabel jLabelProtein3;
    private javax.swing.JLabel jLabelTBMI;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JLabel jLabelVitamin2;
    private javax.swing.JLabel jLabelVitamin3;
    private javax.swing.JLabel jLabelVitamins;
    private javax.swing.JLabel jLabelWeight;
    private javax.swing.JLabel jLabelheight;
    private javax.swing.JLabel jLabelsupper;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldHeight;
    private javax.swing.JLabel jTextFieldUserNamep;
    private javax.swing.JTextField jTextFieldWeight;
    // End of variables declaration//GEN-END:variables
}
