/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dietadvisor;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class patient extends javax.swing.JFrame {

    String Fname;

    /**
     * Creates new form patient
     */
    public patient() {

        initComponents();

    }
   

    /**
     *
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabelUserName = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jButtonSign = new javax.swing.JButton();
        jPasswordFieldPswd = new javax.swing.JPasswordField();
        jTextFieldUserName = new javax.swing.JTextField();
        jLabelError = new javax.swing.JLabel();
        jLabelError1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0,0,0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/LOGO.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, 165));

        jLabelUserName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        jLabelUserName.setText("USER-NAME:");
        jPanel1.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jLabelPassword.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/password.png"))); // NOI18N
        jLabelPassword.setText("PASSWORD");
        jPanel1.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jButtonSign.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonSign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login (1).png"))); // NOI18N
        jButtonSign.setText("SIGN IN");
        jButtonSign.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, null));
        jButtonSign.setContentAreaFilled(false);
        jButtonSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSignMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 141, -1));

        jPasswordFieldPswd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(jPasswordFieldPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 343, 257, 30));

        jTextFieldUserName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(jTextFieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 257, 30));

        jLabelError.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelError.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError.setText("*");
        jPanel1.add(jLabelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(946, 288, -1, -1));

        jLabelError1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelError1.setForeground(new java.awt.Color(255, 0, 0));
        jLabelError1.setText("*");
        jPanel1.add(jLabelError1, new org.netbeans.lib.awtextra.AbsoluteConstraints(946, 342, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("HOMEPAGE");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hos.jpeg"))); // NOI18N
        jLabel1.setAutoscrolls(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, 350));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    public void setUname(String users){
//        users=jTextFieldUserName.getText();
//        Uname=users;
//        System.out.println(Uname);
//    }
//    public String getUname(){
//        System.out.println(Uname);
//    return Uname;
                                      ////

 

                                          ////
//    public void setFname() {
//        
//        Fname =jTextFieldUserName.getText();
//    }
//
    public String getFname() {

        return Fname;
    }
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        index index = new index();
        index.main(null);
        this.dispose();
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButtonSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSignMouseClicked
        // TODO add your handling code here:
        Connection con;
        PreparedStatement ps;
        try {
            con = connection.getConnection();
            ps = con.prepareStatement("SELECT * FROM patient WHERE Name = '" + jTextFieldUserName.getText() + "'" + " AND Password= '" + jPasswordFieldPswd.getText() + "'");
            ResultSet rst = ps.executeQuery();
            if (rst.next()) {
                try { 
                    registeredPatient pp = new registeredPatient();
                    pp.setLocationRelativeTo(null);
                    pp.setVisible(true);
                    
                } catch (Exception e) {
                    System.out.println("error error " + e);
                }

//                Uname = users;
//                System.out.println(Uname);
            } else {
                if (jTextFieldUserName.getText() == " " || jLabelPassword.getText() == " ") {
                    jLabelError1.setVisible(true);
                    jLabelError.setVisible(true);
                    JOptionPane.showMessageDialog(null, "One of more field are empty");
                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect log in details");
                    jTextFieldUserName.setText(null);
                    jPasswordFieldPswd.setText(null);
                }
            }
        } catch (Exception ex) {
            System.out.println("ERR1: " + ex);
        }
    }//GEN-LAST:event_jButtonSignMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButtonSign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelError1;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldPswd;
    public static javax.swing.JTextField jTextFieldUserName;
    // End of variables declaration//GEN-END:variables
}
