/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dietadvisor;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javax.swing.ButtonGroup;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import net.sourceforge.jdatepicker.impl.JDatePanelImpl;
import net.sourceforge.jdatepicker.impl.JDatePickerImpl;
import net.sourceforge.jdatepicker.impl.UtilDateModel;


/**
 *
 * @author user
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
         DateTimeFormatter dtf=DateTimeFormatter.ofPattern("yyyy/MM/dd");
       LocalDateTime now=LocalDateTime.now();
       
        initComponents();
        jRadioButtonPregnant.setVisible(false);
        jRadioButtonPostnatal.setVisible(false);
        ButtonGroup bg=new ButtonGroup();
        bg.add(jRadioButtonHiv);
        bg.add(jRadioButtonDiabetes);
        bg.add(jRadioButtonA);
        bg.add(jRadioButtonB);
        bg.add(jRadioButtonOther);
        bg.add(jRadioButtonAll);
        
 jTextFieldDate2.setText(dtf.format(now));
 
       jRadioButtonA.setVisible(false);
       jRadioButtonB.setVisible(false);
       jTextAreaOthers.setVisible(false);
       
       
        ButtonGroup lch=new ButtonGroup();
        lch.add(jCheckBoxFemale);
        lch.add(jCheckBoxMale);
        lch.add(jCheckBoxOthers);
        
        ButtonGroup supper=new ButtonGroup();
        
        ButtonGroup btn=new ButtonGroup();
        btn.add(jRadioButtonPregnant);
        btn.add(jRadioButtonPostnatal);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelUserName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jButtonSign = new javax.swing.JButton();
        jLabelPassword1 = new javax.swing.JLabel();
        jLabelUserName1 = new javax.swing.JLabel();
        jLabelPassword2 = new javax.swing.JLabel();
        jLabelUserName2 = new javax.swing.JLabel();
        jLabelPassword3 = new javax.swing.JLabel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jLabelUserName3 = new javax.swing.JLabel();
        jLabelPassword4 = new javax.swing.JLabel();
        jPasswordFieldpswd = new javax.swing.JPasswordField();
        jLabelUserName4 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldIdNo = new javax.swing.JTextField();
        jComboBoxLocation = new javax.swing.JComboBox<>();
        jRadioButtonHiv = new javax.swing.JRadioButton();
        jRadioButtonDiabetes = new javax.swing.JRadioButton();
        jRadioButtonA = new javax.swing.JRadioButton();
        jRadioButtonB = new javax.swing.JRadioButton();
        jRadioButtonAll = new javax.swing.JRadioButton();
        jRadioButtonOther = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaOthers = new javax.swing.JTextArea();
        jCheckBoxFemale = new javax.swing.JCheckBox();
        jCheckBoxMale = new javax.swing.JCheckBox();
        jCheckBoxOthers = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDate2 = new javax.swing.JTextField();
        jTextFieldDate = new javax.swing.JTextField();
        jRadioButtonPregnant = new javax.swing.JRadioButton();
        jRadioButtonPostnatal = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(101, 90, 90));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelUserName.setBackground(new java.awt.Color(121, 13, 62));
        jLabelUserName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelUserName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName.setText("NAME:");
        jPanel1.add(jLabelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 75, -1, -1));

        jTextFieldName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 76, 325, -1));

        jLabelPassword.setBackground(new java.awt.Color(121, 13, 62));
        jLabelPassword.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("GENDER");
        jPanel1.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        jButtonSign.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSign.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButtonSign.setText("REGISTER");
        jButtonSign.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSign.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSignMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 560, 124, 35));

        jLabelPassword1.setBackground(new java.awt.Color(121, 13, 62));
        jLabelPassword1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelPassword1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword1.setText("LOCATION");
        jPanel1.add(jLabelPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        jLabelUserName1.setBackground(new java.awt.Color(121, 13, 62));
        jLabelUserName1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelUserName1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName1.setText("D.O.B");
        jPanel1.add(jLabelUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 146, -1, -1));

        jLabelPassword2.setBackground(new java.awt.Color(121, 13, 62));
        jLabelPassword2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelPassword2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword2.setText("EMAIL");
        jPanel1.add(jLabelPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 444, -1, -1));

        jLabelUserName2.setBackground(new java.awt.Color(121, 13, 62));
        jLabelUserName2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelUserName2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName2.setText("DISEASE");
        jPanel1.add(jLabelUserName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabelPassword3.setBackground(new java.awt.Color(121, 13, 62));
        jLabelPassword3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelPassword3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword3.setText("ID NO");
        jPanel1.add(jLabelPassword3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 119, -1, 17));

        jTextFieldPhoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneNumberActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 329, 22));

        jLabelUserName3.setBackground(new java.awt.Color(121, 13, 62));
        jLabelUserName3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelUserName3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName3.setText("PHONE NUMBER");
        jPanel1.add(jLabelUserName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 403, -1, -1));

        jLabelPassword4.setBackground(new java.awt.Color(121, 13, 62));
        jLabelPassword4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelPassword4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword4.setText("PASSWORD");
        jPanel1.add(jLabelPassword4, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 513, -1, -1));

        jPasswordFieldpswd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(jPasswordFieldpswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 330, -1));

        jLabelUserName4.setBackground(new java.awt.Color(121, 13, 62));
        jLabelUserName4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelUserName4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUserName4.setText("DATE OF VISIT");
        jPanel1.add(jLabelUserName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 479, -1, -1));
        jPanel1.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 331, 22));

        jTextFieldIdNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFieldIdNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdNoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldIdNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 117, 325, -1));

        jComboBoxLocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AWENDO", "NYATIKE", "RONGO", "DEDE", "BONDO", " " }));
        jPanel1.add(jComboBoxLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 315, -1));

        jRadioButtonHiv.setText("HIV/AIDS");
        jPanel1.add(jRadioButtonHiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        jRadioButtonDiabetes.setText("DIABETES");
        jRadioButtonDiabetes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonDiabetesMouseClicked(evt);
            }
        });
        jRadioButtonDiabetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDiabetesActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButtonDiabetes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        jRadioButtonA.setText("TYPE A");
        jPanel1.add(jRadioButtonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 70, -1));

        jRadioButtonB.setText("TYPE B");
        jPanel1.add(jRadioButtonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, -1));

        jRadioButtonAll.setText("HIV/AIDS&DIABETES");
        jPanel1.add(jRadioButtonAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        jRadioButtonOther.setText("OTHERS");
        jRadioButtonOther.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonOtherMouseClicked(evt);
            }
        });
        jPanel1.add(jRadioButtonOther, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        jTextAreaOthers.setColumns(20);
        jTextAreaOthers.setRows(5);
        jScrollPane1.setViewportView(jTextAreaOthers);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 341, 67));

        jCheckBoxFemale.setText("FEMALE");
        jCheckBoxFemale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxFemaleMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jCheckBoxMale.setText("MALE");
        jCheckBoxMale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxMaleMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        jCheckBoxOthers.setText("OTHERS");
        jPanel1.add(jCheckBoxOthers, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 570, -1, -1));

        jLabel1.setBackground(new java.awt.Color(121, 13, 62));
        jLabel1.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTER PATIENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 35, 302, 34));

        jTextFieldDate2.setEditable(false);
        jTextFieldDate2.setText("YYYY-MM-DD");
        jTextFieldDate2.setToolTipText("Today");
        jPanel1.add(jTextFieldDate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 331, -1));

        jTextFieldDate.setText("YYYY-MM-DD");
        jTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 149, 203, -1));

        jRadioButtonPregnant.setText("PREGNANT");
        jPanel1.add(jRadioButtonPregnant, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        jRadioButtonPostnatal.setText("POST NATAL");
        jPanel1.add(jRadioButtonPostnatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSignMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSignMouseClicked
       //disease
        String Disease=null;
       if(jRadioButtonHiv.isSelected()){
        Disease="HIV";
        }
       else if(jRadioButtonDiabetes.isSelected()){
        Disease="Diabetes";
        }
       else if(jRadioButtonA.isSelected()){
        Disease="Diabetes_A";
        }
        else if(jRadioButtonB.isSelected()){
        Disease="Diabetes_B";
        }
        else if(jRadioButtonOther.isSelected()){
        Disease=("Other");
        }
        else if(jRadioButtonAll.isSelected()){
        Disease="jTextAreaOthers";
        }
       //disease
       String Gender=null;
       if(jCheckBoxFemale.isSelected()){
           Gender="Female";
       }
       else if(jCheckBoxMale.isSelected()){
           Gender="Male";
       }
       else{
            Gender="Others";
       }
       if(jCheckBoxFemale.isSelected()){
        jRadioButtonPregnant.setVisible(true);
        jRadioButtonPostnatal.setVisible(true);
       }
       String status=null;
       if(jRadioButtonPregnant.isSelected()){
       status="pregnant";
       }
       else if(jRadioButtonPostnatal.isSelected()){
       status="postnatal";
       }
       if(jCheckBoxMale.isSelected()){
       status="X";
       }
       int age;
     
       
       //Location
       String Location=jComboBoxLocation.getSelectedItem().toString();
       
       //Location
        Connection con;
        PreparedStatement ps;
        try{
        con=connection.getConnection();
        ps=con.prepareStatement("INSERT INTO patient (Name,Id_no,DOB,Location,Disease,E_mail, Phone_no,Gender,Status,DOV,Password) VALUES(?,?,?,?,?,?,?,?,?,?,?)");
        ps.setString(1,jTextFieldName.getText());
        ps.setString(2,jTextFieldIdNo.getText());
        ps.setString(3,jTextFieldDate.getText());
        ps.setString(4,Location );
        ps.setString(5,Disease);
        ps.setString(6,jTextFieldEmail.getText());
        ps.setString(7,jTextFieldPhoneNumber.getText());
        ps.setString(8,Gender);
        ps.setString(9, status);
        ps.setString(10, jTextFieldDate2.getText());
        ps.setString(11,jPasswordFieldpswd.getText());
        
//        int i=ps.executeUpdate();
        if(ps.executeUpdate()>0){
        JOptionPane.showMessageDialog(null,"registered "+jTextFieldName.getText());
        }
        else{
        JOptionPane.showMessageDialog(null,"cannot register "+jTextFieldName.getText());
        }
          }catch(Exception e){
        System.out.println("err: "+e);
        
        }
    }//GEN-LAST:event_jButtonSignMouseClicked

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNumberActionPerformed

    private void jTextFieldIdNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdNoActionPerformed

    private void jRadioButtonDiabetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDiabetesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonDiabetesActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       Doctor dr=new Doctor();
       dr.main(null);
       this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jRadioButtonDiabetesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonDiabetesMouseClicked
      if(jRadioButtonDiabetes.isSelected()){
jRadioButtonDiabetes.setVisible(false);
jRadioButtonA.setVisible(true);
jRadioButtonB.setVisible(true);
      }
    }//GEN-LAST:event_jRadioButtonDiabetesMouseClicked

    private void jRadioButtonOtherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonOtherMouseClicked
       
       if(jRadioButtonB.isSelected()){
       jTextAreaOthers.setVisible(false);
       }
       else if(jRadioButtonHiv.isSelected()){
       jTextAreaOthers.setVisible(false);
       }
        else if(jRadioButtonDiabetes.isSelected()){
       jTextAreaOthers.setVisible(false);
       }
        else if(jRadioButtonAll.isSelected()){
       jTextAreaOthers.setVisible(false);
       }
        else if(jRadioButtonA.isSelected()){
       jTextAreaOthers.setVisible(false);
       }
        else if(jRadioButtonOther.isSelected()){
       jTextAreaOthers.setVisible(true);
       }
       
    }//GEN-LAST:event_jRadioButtonOtherMouseClicked

    private void jTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateActionPerformed

    private void jCheckBoxFemaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxFemaleMouseClicked
        // TODO add your handling code here:
                jRadioButtonPregnant.setVisible(true);
                 jRadioButtonPostnatal.setVisible(true);
    }//GEN-LAST:event_jCheckBoxFemaleMouseClicked

    private void jCheckBoxMaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxMaleMouseClicked
        // TODO add your handling code here:
                        jRadioButtonPregnant.setVisible(false);
                        jRadioButtonPostnatal.setVisible(false);
    }//GEN-LAST:event_jCheckBoxMaleMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonSign;
    private javax.swing.JCheckBox jCheckBoxFemale;
    private javax.swing.JCheckBox jCheckBoxMale;
    private javax.swing.JCheckBox jCheckBoxOthers;
    private javax.swing.JComboBox<String> jComboBoxLocation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPassword1;
    private javax.swing.JLabel jLabelPassword2;
    private javax.swing.JLabel jLabelPassword3;
    private javax.swing.JLabel jLabelPassword4;
    private javax.swing.JLabel jLabelUserName;
    private javax.swing.JLabel jLabelUserName1;
    private javax.swing.JLabel jLabelUserName2;
    private javax.swing.JLabel jLabelUserName3;
    private javax.swing.JLabel jLabelUserName4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldpswd;
    private javax.swing.JRadioButton jRadioButtonA;
    private javax.swing.JRadioButton jRadioButtonAll;
    private javax.swing.JRadioButton jRadioButtonB;
    private javax.swing.JRadioButton jRadioButtonDiabetes;
    private javax.swing.JRadioButton jRadioButtonHiv;
    private javax.swing.JRadioButton jRadioButtonOther;
    private javax.swing.JRadioButton jRadioButtonPostnatal;
    private javax.swing.JRadioButton jRadioButtonPregnant;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaOthers;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldDate2;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIdNo;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
